### ISSUE TITLE
Error During Install

### ISSUE THREAD

**Issue by kishori-sharan** [nomadicjosh/eduTrac-SIS#19]
Hello, 
I have been trying to install eduTrac on Windows 10. When I execute "./etsis core migrate" command, I get the following error:

 '.' is not recognized as an internal or external command, operable program or batch file.

I have debugged the issue down to etsis_CLI.php file. The error is received when $instance is created.

echo  'Impl: ', var_dump($implementation),  "\n";
echo  'Args: ', var_dump($arguments),  "\n";
echo  'Assoc: ', var_dump($assoc_args),  "\n";
$instance = new $implementation($arguments, $assoc_args);
echo "Error occurs here";

My output is:
Impl: string(12) "Core_Command"

Args: array(1) {
  [0]=>
  string(7) "migrate"
}

Assoc: array(0) {
}

'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kishori-sharan** [comment]
I found a work around. I used teh following command instead:

$ ./phinx migrate -e production

It worked. However, I had to fix the database script that inserts a row in the person table. The database script "insert into 'person'" and "create table 'person'" are not in sync. several NOT NULL with no default value have been added to teh 'person' table, but the "insert into 'person'" script does not add values for those field.

Also fields on the "Add Person" screen are not in sync with the 'person' table fields. 

Thanks
Kishori

**Comment by nomadicjosh** [comment]
Hmm, never saw this issue. I don't understand what you are saying about the person table and null values. Can you explain future.

**Comment by kishori-sharan** [comment]
Sure. here are the details. I would be glad to provide more info that helps you track it down.

The app\migrations\20160916002812_initial_schema.php file contains the following line of code that inserts a record in the 'person' table:

$this->execute('INSERT INTO `person` (`personID`, `uname`, `password`, `fname`, `lname`, `email`,`personType`,`approvedDate`,`approvedBy`) VALUES (\'\', \'etsis\', \'$P$BAHklrhrmcZMglABG9VF6PB7c1zD5H/\', \'eduTrac\', \'SIS\', \'sis@gmail.com\', \'STA\', \'' . $NOW . '\', \'1\');');

I changed it to the following to make it work:

$this->execute('INSERT INTO `person` (`LastLogin`, `emergency_contact_phone`, `emergency_contact`, `nationality`, `ethnicity`, `dob`, `ssn`, `personID`, `prefix`, `mname`, `uname`, `password`, `fname`, `lname`, `email`,`personType`,`approvedDate`,`approvedBy`) VALUES (\''.$NOW.'\', \'111223456\', \'Kannan\', \'US\', \'Asian\', \''.$NOW.'\', 111223333, NULL, \'Mr.\', \'M\', \'etsis\', \'$P$BAHklrhrmcZMglABG9VF6PB7c1zD5H/\', \'eduTrac\', \'SIS\', \'sis@gmail.com\', \'STA\', \''.$NOW.'\', \'1\');');


You can see that I have added the following fields and supplied their values:
`LastLogin`, `emergency_contact_phone`, `emergency_contact`, `nationality`, `ethnicity`, `dob`, `ssn`,  `prefix`, `mname`

I also had to set personID to NULL instead of the empty string ''.  This could be my MySQL setting that was complaining that an empty string ('') is not allowed in an integer field 'personID'.

To make the Add Person screen work, I had to execute the following alter table commands:

ALTER TABLE edutrac.person MODIFY COLUMN nationality VARCHAR(11) NULL;

ALTER TABLE edutrac.person MODIFY COLUMN LastLogin DATETIME NULL;

Another issue that I had was when I click the "Save" button on the Add Person screen. It adds a record and takes me to a blank screen. A feedback would be better when the add is successful.


Thanks
Kishori

**Comment by nomadicjosh** [comment]
Thanks, but all those seem to be a MySQL version issue. I believe anything below a MySQL 5.6 will complain about empty strings and MySQL 5.6 is the minimum requirement. Please confirm.

> Another issue that I had was when I click the "Save" button on the Add Person screen. It adds a record and takes me to a blank screen. A feedback would be better when the add is successful.

Then it was not successful. It might have inserted the data into the database, but if the screen returned blank, then it was not successful. It could be a setting or it could be a bug. Error logs can help determine which.

**Comment by kishori-sharan** [comment]
I am using MySQL 5.7

**Comment by nomadicjosh** [comment]
Ok, I think the issue might be with the foreign key because it accepts null but not empty string. I will do some changes and testing on this. Thanks for the info.
