### ISSUE TITLE
Sign in issues 

### ISSUE THREAD

**Issue by ghost** [nomadicjosh/eduTrac-SIS#20]
hi Joshua
i had Sign in issues for 6.3.0-RC3 .
when i try to Sign in it's redirect me to first page without any login effect 
i using  Username: etsis Password: edutracsis what you are put it to used for first login

![screenshot from 2017-03-02 12-28-46](https://cloud.githubusercontent.com/assets/24421498/23504498/6e3881f2-ff48-11e6-8df2-45d7624ab90d.png)

i know it's unstable version 
i had other issues for 6.2.12 but it's more complicit we will take about it in another time

**Comment by nomadicjosh** [comment]
Check the error logs (app/tmp/logs) to make sure you are not having permission issues.

**Comment by ghost** [comment]
there is no errors in app/tmp/logs

**Comment by nomadicjosh** [comment]
Are there any new files or directories in the root that were not there before (i.e. option)?

**Comment by ghost** [comment]
No

**Comment by nomadicjosh** [comment]
So, you get no error message anywhere that can help me to help you?

**Comment by ghost** [comment]
that is all logs i found it 
![screenshot from 2017-03-02 17-01-27](https://cloud.githubusercontent.com/assets/24421498/23512679/1b5e7c8a-ff6a-11e6-8477-f34e280e2da7.png)
![screenshot from 2017-03-02 16-56-58](https://cloud.githubusercontent.com/assets/24421498/23512680/1b651d24-ff6a-11e6-93b7-18ac712a1836.png)

**Comment by nomadicjosh** [comment]
If you don't mind sending me FTP and database details, use the contact form at the bottom of this page: [https://www.edutracsis.com/support/](https://www.edutracsis.com/support/)
