### ISSUE TITLE
Registration issue version 6.2.11

### ISSUE THREAD

**Issue by ghost** [nomadicjosh/eduTrac-SIS#21]
I have an issue when registering a new student to a certain section, the following error message appears and the student is not registered in the database or anywhere else. I tried registering the student directly through the database (manually), but even then it didn't sync with the moodle plugin that I've installed. What is meant by this issue and how can I resolve it?
I think if we solve the registration issue, the moodle sync will be solved.
![screenshot from 2017-03-05 11-54-32](https://cloud.githubusercontent.com/assets/24421498/23586325/70459840-019b-11e7-9cfb-284ac988f954.png)
![screenshot from 2017-03-05 11-50-23](https://cloud.githubusercontent.com/assets/24421498/23586328/752953a6-019b-11e7-839c-f2248d426b78.png)

**Comment by glassofmilk13** [comment]
The same problem happened to me, I can't register any new students to a course. Help would be appreciated.

**Comment by nomadicjosh** [comment]
If you manually add it to the database, then you've bypassed both etSIS and Moodle and there is no sync. With regards to the error, is the person an actual student? Does a student record exist for this person in the student table?

**Comment by ghost** [comment]
yes is an actual student and have record on student table 
![screenshot from 2017-03-06 08-46-05](https://cloud.githubusercontent.com/assets/24421498/23599412/91edc8ba-0249-11e7-9d1b-fc28aaed47e8.png)

**Comment by nomadicjosh** [comment]
Your last image is not an image of student records, it is an image of person records.
