### ISSUE TITLE
Post in News & Announcements

### ISSUE THREAD

**Issue by jafinol** [nomadicjosh/eduTrac-SIS#22]
How can I do to publish in News & Announcements? thanks

**Comment by nomadicjosh** [comment]
Do you have the myetsis extended module installed?

**Comment by jafinol** [comment]
yes my friend

**Comment by nomadicjosh** [comment]
On the homepage when you are logged in, in the upper right hand corner, you should see Admin. Click it and it will take you to the place to add links, news, and pages.
