### ISSUE TITLE
Database error in instalation 6.2.12

### ISSUE THREAD

**Issue by trevis2001** [nomadicjosh/eduTrac-SIS#23]
When i run index.php in my server, this error message is displayed :

[03-Apr-2017 08:57:32 America/Sao_Paulo] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'atinfoco_edutrac.plugin' doesn't exist' in /home/atinfoco/public_html/edutrac/Liten/Orm.php:247
Stack trace:
#0 /home/atinfoco/public_html/edutrac/Liten/Orm.php(247): PDOStatement->execute(Array)
#1 /home/atinfoco/public_html/edutrac/Liten/Orm.php(313): Liten\Orm->query('SELECT \n\t plugi...', Array)
#2 /home/atinfoco/public_html/edutrac/app/src/Hooks.php(231): Liten\Orm->find(Object(Closure))
#3 /home/atinfoco/public_html/edutrac/app/functions/hook-function.php(83): app\src\Hooks->load_activated_plugins('/home/atinfoco/...')
#4 /home/atinfoco/public_html/edutrac/app/functions/hook-function.php(554): load_activated_plugins('/home/atinfoco/...')
#5 /home/atinfoco/public_html/edutrac/config.php(118): require('/home/atinfoco/...')
#6 /home/atinfoco/public_html/edutrac/index.php(27): include('/home/atinfoco/...')
#7 {main}
  thrown in /home/atinfoco/public_html/edutrac/Liten/Orm.php on line 247

**Comment by nomadicjosh** [comment]
Did you run the installer to create the database tables and config.php file?

**Comment by trevis2001** [comment]
I checked that i didn´t run the installer.
The database can be installed only by  "./etsis core install" ? 
Are there another way to install the database ?

**Comment by nomadicjosh** [comment]
No, installation and upgrades are done via command line.
