### ISSUE TITLE
Can not View Home page of eduTrac-SIS

### ISSUE THREAD

**Issue by Eng-ganna** [nomadicjosh/eduTrac-SIS#24]
Hello Everyone,

I followed the installation Steps of eduTrac-SIS through this link
https://www.edutracsis.com/manual/installation/
without any problems
But I changed the port on apache2 to 8072 because port 80 is used by other application
when I browse the app through

http://serverip:8072

it login on apache2 homepage not on eduTrace
I can not access eduTrace
please help me in access it
Thanks

**Comment by nomadicjosh** [comment]
I can't help you with server issues. Error logs may be helpful.

**Comment by Eng-ganna** [comment]
Sorry , but the web site is not accessible on web interface , I can not find it
it is not server issue , I entered on path /etc/apache2/sites-available
and I donot find EduTraceSIS web Site
I also donot know the way to access eduTrace on web interface

I reinstalled the edutracesis on new server using https://www.edutracsis.com/manual/installation/
without any further changes 

can you guide me to the way to find this web site on apache2 web server and how can I access it?
the final step that I did it is 
./etsis core migrate

and  in installation guide in https://www.edutracsis.com/manual/installation/
I found that the web site must be accessible
how ?, I can not access it

Please what is the lost step?

**Comment by nomadicjosh** [comment]
If you are using MAMP for example, and you install in root, then you can access it at http://localhost:8888/ or if in a subdirectory called etsis, then access it at http://localhost:8888/etsis/. It depends where you installed it. If you can access it at http://serverip:8072, then maybe it is only accessible at http://serverip/.

**Comment by Eng-ganna** [comment]
I use LAMP server on Ubuntu 16
and I use root user
then installed using the following steps:
1-git clone https://github.com/parkerj/eduTrac-SIS.git

Note:
the folder of edutracesis in root home is called eduTrac-SIS

2-Create database
3-Create user and give it full control on database
4-change permission on installed edutracsis folder in root home to 777
5-enter database details in phinx.php
6-install using    ./etsis core migrate    -->it is successfull

But I can not access it using 
http://localhost   or http://localhost:8888

**Comment by nomadicjosh** [comment]
I stated that it depends on where you install it. I used _localhost_ as an example. You need visit the url where it is installed. If it does not show up, then you need to check error logs (app/tmp/logs/*.txt) for where the issue is or visit [here](https://www.edutracsis.com/wiki/debugging-edutrac-sis/) for debugging help.

**Comment by gsons** [comment]
## i am very angry
### i can't see anything  when i open home page,it show blank
### can everyone help me to solve the problem, i will thank you
