### ISSUE TITLE
_mkdir Function Fails on MAC OS Sierra

### ISSUE THREAD

**Issue by freelancewebdev** [nomadicjosh/eduTrac-SIS#40]
In the file etsis_Cache_Filesystem.php there are a couple of references to a function _mkdir.  Despite having set my cache folder permissions and ownership appropriately, this function does not seem to work.

As a temporary workaround I have changed that function to the standard PHP mkdir function and that functions correctly but obviously it's not ideal to be editing core files.

This seems to be MAC OS specific as I didn't have the problem on a test instance running on Ubuntu.

EduTracSIS Release: 6.3.3
MySQL 5.7
PHP 7.1.4
Apache 2.24
MACOS Sierra

**Comment by nomadicjosh** [comment]
Well, you probably have error logs in app/tmp/logs/*.txt which probably tells you that the session_savepath is not writable or not set. Which means that you need to set the session_savepath in your php.ini file. The path is usually set to /tmp.

**Comment by freelancewebdev** [comment]
You're right.  the session.save_path entry wasn't set.  I have set it to a folder with the correct permissions and ownership.

But that hasn't solved the issue with both node and cache files not being written.   

I should say that I have updated the config.php file and set my directory for session storage there so that the app knows where to place the node and cache files.  Just for testing, after adding the session.save_path value in php.ini and restarting Apache, I then took my existing session folder (the one named after the subdomain), renamed it and made an empty folder with the same name and ownership chomped to 777.  I then switched back the two _mkdir function calls and tried accessing the app, essentially with a cleared cache and once again, I got error messages about not being able to open the node files for writing.

**Comment by nomadicjosh** [comment]
What do the error messages say exactly? What server client are you using (i.e. AMPPS, MAMP, XAMPP, etc)?

**Comment by freelancewebdev** [comment]
Some further investigation which I'm not sure is helpful.  The error about my session.save_path is gone in the apache error log but I now see:
[2017-08-11 20:52:12] error.ERROR: NODEQSTATE[0]: Field rule does not exists in node "alst" [] []
[2017-08-11 20:52:12] error.ERROR: NODEQSTATE[0]: Field rule does not exists in node "stld" [] []
[2017-08-11 20:52:12] error.ERROR: NODEQSTATE[0]: Field rule does not exists in node "clvr" [] []
[2017-08-11 20:52:12] error.ERROR: NODEQSTATE[0]: Field rule does not exists in node "rrsr" [] []

I'm using the Apache instance that comes with Sierra and my PHP from https://php-osx.liip.ch/ (7.1.4) and MySQL installed from the DMG from Oracle - had to change the sql-mode to an empty string in my.conf to get that working.

**Comment by freelancewebdev** [comment]
Hmmm, well we are making some progress because I can now see the nodes folder being created
What I see in the browser (paths hidden for privacy but it is correct)
Warning: file_put_contents(/path-to-session-subdomain/nodes/etsis/rlde.data.node): failed to open stream: No such file or directory in /path to web root/app/src/Core/NodeQ/Helpers/File.php on line 66


1 | 0.0006 | 366624 | {main}( ) | .../index.php:0
2 | 0.0020 | 406376 | include( '/path to web root/config.php' ) | .../index.php:27
3 | 0.0100 | 1104944 | require( '/path to web root/app/functions/dependency.php' ) | .../config.php:120
4 | 0.0184 | 1843896 | require( '/path to web root/app/functions/rules-function.php' ) | .../dependency.php:687
5 | 0.0205 | 1963664 | app\src\Core\NodeQ\etsis_NodeQ::dispense( ) | .../rules-function.php:28
6 | 0.0214 | 2081224 | app\src\Core\NodeQ\Helpers\Migrations::dispense( ) | .../etsis_NodeQ.php:22
7 | 0.0228 | 2120480 | app\src\Core\NodeQ\Helpers\Migrations::rlde( ) | .../Migrations.php:18
8 | 0.0228 | 2120480 | app\src\Core\NodeQ\CoreDatabase::create( ) | .../Migrations.php:294
9 | 0.0229 | 2121768 | app\src\Core\NodeQ\Helpers\File->put( ) | .../CoreDatabase.php:287
10 | 0.0229 | 2122136 | file_put_contents ( ) | .../File.php:66

**Comment by freelancewebdev** [comment]
Actually logging out and logging back in sorted those errors.

You would think I would have tried that quicker - thanks for your help!

**Comment by nomadicjosh** [comment]
Okay, so now that your session_savepath is set, and you set a different path in config.php, your nodes have been created and there are no other errors?

**Comment by freelancewebdev** [comment]
Nope, all good thanks - closing the issue.
