### ISSUE TITLE
Apostrophes in Person Last Name Converted to Unicode HTML Entities 

### ISSUE THREAD

**Issue by freelancewebdev** [nomadicjosh/eduTrac-SIS#41]
I'm in Ireland and so there are quite a few people with surnames including apostrophes - O'Loughlin, O'Donnell etc.

When such names are saved in the person table, as the title says, the apostrophes are converted to their unicode HTML entity equivalent which is then displayed raw as '&#39;' in the person view screen.

**Comment by nomadicjosh** [comment]
Open _app/views/person/view.php_. Search for every instance of `_h(` and replace it with `_escape(`.

**Comment by freelancewebdev** [comment]
Thanks.  Would you like me to close these as we go?

**Comment by nomadicjosh** [comment]
Yes.
