### ISSUE TITLE
Issues with course / course section

### ISSUE THREAD

**Issue by CCNYCPSSupport** [nomadicjosh/eduTrac-SIS#43]
I understand you implemented the inability to delete courses and sections. Though very counter intuitive, I cannot seem to make it inactive either because when i switch it, there is no save button! 

Now Im sure there must be something Im doing wrong, because this would cause so many issues. Having students register for classes that were created by mistake is not what we want!

Please advise

**Comment by nomadicjosh** [comment]
Something about this scenario doesn't make sense. So, you can activate a course section, but you can't deactivate or make the course section inactive or obsolete?
