### ISSUE TITLE
r6.3.4 - missing menu on some pages

### ISSUE THREAD

**Issue by apmuthu** [nomadicjosh/eduTrac-SIS#44]
On a fresh install of EduTrac-SIS r6.3.4 on Debian 8.9 Jessie:

- there were some lookup pages that did not display the left menu like 

1. Dashboard -> Snapshot Report
2. Student -> Student lookup

- atleast 1 page where a blank page appears - **(BRGN) - Batch Reg**: `/sect/brgn/`
- atleast 1 page - **Section -> Gradebook -> My Course Sections** with a page not found: `/sect/courses/`

**Comment by nomadicjosh** [comment]
The left menu does not show on those screens. BRGN and the Gradebook shouldn't show up if you don't have those modules installed, so that will be fixed in the next release.

**Comment by apmuthu** [comment]
Why is it necessary to register to download the plugins / modules? Are they commercial ones? If not, where are the repos that host them? Other than [degree-audit](https://github.com/parkerj/degree-audit) plugin dated over a year and a half ago, I see no links for the useful extensions.

**Comment by apmuthu** [comment]
Yes, the [Plugins](https://plugins.edutracsis.com/) link is there.

The moodle plugin does not download. Something else covers the page as well.
![2017-11-15_005655](https://user-images.githubusercontent.com/2995044/32800298-f46ce6b0-c99f-11e7-9938-20b03ee9dfd8.png)

**Comment by apmuthu** [comment]
There is still no way to directly download the moodle plugin. The description should clearly state that a registration is needed to download it, if that is the intention. Expecting a Tweet, Like, Google+ or LinkedIn(absent link) to download puts those not on such sites at a disadvantage.

Also, it is over 3 years old. Is there any GitHub/SF link to it that can be forked and developed?
