### ISSUE TITLE
Could not create the file cache directory

### ISSUE THREAD

**Issue by ommae** [nomadicjosh/eduTrac-SIS#46]
Immediately after installation, I get the error:

`Fatal error: Uncaught app\src\Core\Exception\IOException 'Could not create the file cache directory.' in /home/pucsr096/public_html/eduTracSis/app/src/Core/Cache/etsis_Cache_Filesystem.php(166) #0 /home/pucsr096/public_html/eduTracSis/app/src/Core/Cache/etsis_Object_Cache.php(42): app\src\Core\Cache\etsis_Cache_Filesystem->__construct() #1 /home/pucsr096/public_html/eduTracSis/app/functions/global-function.php(26): app\src\Core\Cache\etsis_Object_Cache->__construct('file') #2 /home/pucsr096/public_html/eduTracSis/app/functions/cache-function.php(60): _etsis_cache_init() #3 /home/pucsr096/public_html/eduTracSis/app/src/Hooks.php(819): etsis_cache_get('system_email', 'option') #4 /home/pucsr096/public_html/eduTracSis/app/functions/logger-function.php(74): app\src\Hooks->get_option('system_email') #5 /home/pucsr096/public_html/eduTracSis/app/functions/dependency.php(693): require('/home/pucsr096/...') #6 /home/pucsr096/public_html/eduTracSis/config.php(117): require('/home/pucsr096/...') #7 /home/pucsr096/public_html/eduTrac in /home/pucsr096/public_html/eduTracSis/app/src/Core/Cache/etsis_Cache_Filesystem.php on line 166`

config.php was changed to point to /home/pucsr096/etsis_tmp (which has rights of 775) as shown in the installation instructions.

**Comment by nomadicjosh** [comment]
It is definitely a permission issue. 775 might be too high. Have your tried 755? Also make sure that the directories are owned by the proper user and group.
