### ISSUE TITLE
Is the developer of this software still alive?

### ISSUE THREAD

**Issue by j-chase** [nomadicjosh/eduTrac-SIS#50]
We bought this software late last year, and were going through the dev process with Joshua, he was helping us get the system up and running for our needs, but his contact abruptly broke off.
The last message we got from him was that he'd moved from Boston "back" to South Carolina, early in January.
At first we were concerned about our software development, now we're just worried for him.
I don't see any activity here either.
Has anyone heard from Joshua in the last few weeks?
Is he OK?
Honestly worried for the guy, seemed like a nice person.
Any info would be greatly appreciated.

**Comment by nomadicjosh** [comment]
Yes, I am alive and well. I just recently change phone service. So, do you need to/want to set up a time to talk? I have sent you emails, but I am not sure if they were going through.

**Comment by j-chase** [comment]
Thank goodness, we were sincerely worried about you Joshua!
And no, unfortunately we haven't received any correspondence from you in weeks, obviously I checked Spam and Junk folders and filters on all the different computers and devices just to make sure.
Let's take this conversation off public space, you know my phone, and I will email it to you again, at your convenience, text to schedule a time, and we'll have that call.
...not kidding...we were really worried there for a bit...glad you're OK!
:-)

**Comment by nomadicjosh** [comment]
I will say this here in case some how my email gets lost again. I will call you on Monday at 3PM EST.

**Comment by j-chase** [comment]
Whew.
As I mentioned in one of my previous emails, I wear 12 hats around here, and there’s a couple things I’d like to go over with you, but really the one thing right now is just seeing the Moodle integration work.
Please let me know if you need anything to just go into our Moodle and our etSIS and see why they don’t seem to be communicating.
If you’d prefer to do the phone call, I’m in!:
1 (323) 286-2005
Text for scheduling (when it is convenient for you to do so) and we’ll go from there.
Honestly worried for a minute there, glad to hear you’re OK.
J

 

John Chase

IT Dept.

University of Philosophical Research
3910 Los Feliz Blvd. 

Los Angeles, Ca. 90027

Ph.323.663.2167, Ext. 117
tech@uprs.edu

uprs.edu

**Comment by nomadicjosh** [comment]
Not a problem. Send me an email with your etSIS super admin account login, and your Moodle login and I will take a look at it before we talk.
