### ISSUE TITLE
Timesheets

### ISSUE THREAD

**Issue by BereaSchool** [nomadicjosh/eduTrac-SIS#51]
Staff has reported to me that timesheets are not working properly.  The start time and end time continue to be populated with the current time.  They cannot adjust them properly and they are saving as 0 work hours.  Thanks for your help.

**Comment by nomadicjosh** [comment]
Ok, looking into the issue.

**Comment by parkerj** [comment]
Ok, I am looking into it.

**Comment by BereaSchool** [comment]
The screenshots show how I input a specific time, but it always resets to the current time.  It happens to all my staff and they cannot submit their times.

<img width="537" alt="screen shot 1" src="https://user-images.githubusercontent.com/35111092/36007415-52d6ca78-0d10-11e8-8855-6872bcae820f.png">
<img width="537" alt="screen shot 2" src="https://user-images.githubusercontent.com/35111092/36007419-572fceb2-0d10-11e8-8c9a-b929b077ac76.png">
<img width="536" alt="screen shot 3" src="https://user-images.githubusercontent.com/35111092/36007422-5b290c7c-0d10-11e8-97ed-f0f953ff7129.png">

**Comment by nomadicjosh** [comment]
Ah, got it.

**Comment by nomadicjosh** [comment]
Ok, this should be fixed now.
