### ISSUE TITLE
admission page 404

### ISSUE THREAD

**Issue by wajdizoughbi** [nomadicjosh/eduTrac-SIS#52]
please trying to go to /pages/admissions/  
but getting the error
Ouch! 404 error
It seems the page you are looking for is not here anymore. The page might have moved to another address or just removed by our staff.

**Comment by nomadicjosh** [comment]
Admissions' page doesn't exist. It is dummy text.

**Comment by wajdizoughbi** [comment]
well does that mean that the edutrac doesn't have the admission page

**Comment by nomadicjosh** [comment]
That's correct but you can create one if you need one, otherwise you can edit the dummy text to be what ever you want or need.

**Comment by nomadicjosh** [comment]
If you have the [myetSIS Extended Module](https://www.edutracsis.com/kb/system-modules/) installed, you should see an admin menu. If you don't see one, then it is not installed.
