### ISSUE TITLE
register student

### ISSUE THREAD

**Issue by wajdizoughbi** [nomadicjosh/eduTrac-SIS#53]
Hi , i get the message Student ID must be numeric. when registering a student, even the id is numeric

**Comment by nomadicjosh** [comment]
That's not a eduTrac SIS error message. Can you send a screenshot and other error log output that may pertain to that issue.

**Comment by nomadicjosh** [comment]
Ah, I see where this error message is coming from. Are you entering a student's id or name? When doing so, does the system automatically show the student's name to select into that field?

**Comment by nomadicjosh** [comment]
If you look at your GitHub post, there is no image.

**Comment by wajdizoughbi** [comment]
please see below issue
![register issue](https://user-images.githubusercontent.com/36000709/36774275-05d65b7a-1c66-11e8-9808-2998a0b49bf1.png)

**Comment by nomadicjosh** [comment]
When start to type in the student's name or id, the name will populate below. You must select the name in order for the system to populate the student's id in a hidden field that will be posted when you click the Register button.
