### ISSUE TITLE
what to do after ./etsis core migrate

### ISSUE THREAD

**Issue by sumardika** [nomadicjosh/eduTrac-SIS#55]
I have passed ./etsis core migrate. Please help how to proceed? I try to load page from browser http://localhost/edutrac with error

**Comment by nomadicjosh** [comment]
What are you using (windows, Mac, XAMPP, AMPPS, MAMP, etc.)? Does .htaccess exist in the root? Are there any errors in the error log (app/tmp/logs/error*.txt)?

**Comment by sumardika** [comment]
I am using local environment on Mac.
Below are error messages when I access http://localhost/edutrac/

Warning: file_put_contents(/www/nodes/etsis/rlde.data.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_put_contents(/www/nodes/etsis/rlde.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_get_contents(/www/nodes/etsis/rlde.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: Invalid argument supplied for foreach() in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/CoreDatabase.php on line 141

Warning: file_put_contents(/www/nodes/etsis/alst.data.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_put_contents(/www/nodes/etsis/alst.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_get_contents(/www/nodes/etsis/alst.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: array_keys() expects parameter 1 to be array, null given in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/Config.php on line 42

Warning: in_array() expects parameter 2 to be array, null given in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/Validate.php on line 132

Warning: file_get_contents(/www/nodes/etsis/alst.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: Invalid argument supplied for foreach() in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/CoreDatabase.php on line 141

Warning: file_put_contents(/www/nodes/etsis/stld.data.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_put_contents(/www/nodes/etsis/stld.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_get_contents(/www/nodes/etsis/stld.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: array_keys() expects parameter 1 to be array, null given in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/Config.php on line 42

Warning: in_array() expects parameter 2 to be array, null given in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/Validate.php on line 132

Warning: file_get_contents(/www/nodes/etsis/stld.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: Invalid argument supplied for foreach() in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/CoreDatabase.php on line 141

Warning: file_put_contents(/www/nodes/etsis/clvr.data.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_put_contents(/www/nodes/etsis/clvr.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_get_contents(/www/nodes/etsis/clvr.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: array_keys() expects parameter 1 to be array, null given in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/Config.php on line 42

Warning: in_array() expects parameter 2 to be array, null given in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/Validate.php on line 132

Warning: file_get_contents(/www/nodes/etsis/clvr.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: Invalid argument supplied for foreach() in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/CoreDatabase.php on line 141

Warning: file_put_contents(/www/nodes/etsis/rrsr.data.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_put_contents(/www/nodes/etsis/rrsr.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_get_contents(/www/nodes/etsis/rrsr.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: array_keys() expects parameter 1 to be array, null given in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/Config.php on line 42

Warning: in_array() expects parameter 2 to be array, null given in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/Validate.php on line 132

Warning: file_get_contents(/www/nodes/etsis/rrsr.config.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: Invalid argument supplied for foreach() in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/CoreDatabase.php on line 141

Fatal error: Uncaught app\src\Core\Exception\IOException 'Could not create the file cache directory.' in /Users/sumardika/www/edutrac/app/src/Core/Cache/etsis_Cache_Filesystem.php(166) #0 /Users/sumardika/www/edutrac/app/src/Core/Cache/etsis_Object_Cache.php(42): app\src\Core\Cache\etsis_Cache_Filesystem->__construct() #1 /Users/sumardika/www/edutrac/app/functions/global-function.php(26): app\src\Core\Cache\etsis_Object_Cache->__construct('file') #2 /Users/sumardika/www/edutrac/app/functions/cache-function.php(60): _etsis_cache_init() #3 /Users/sumardika/www/edutrac/app/src/Hooks.php(819): etsis_cache_get('system_email', 'option') #4 /Users/sumardika/www/edutrac/app/functions/logger-function.php(74): app\src\Hooks->get_option('system_email') #5 /Users/sumardika/www/edutrac/app/functions/dependency.php(693): require('/Users/sumardik...') #6 /Users/sumardika/www/edutrac/config.php(117): require('/Users/sumardik...') #7 /Users/sumardika/www/edutrac/index.php(27): include('/Users/sumardik...') #8 {main} thrown in /Users/sumardika/www/edutrac/app/src/Core/Cache/etsis_Cache_Filesystem.php on line 166

**Comment by sumardika** [comment]
Are there any errors in the error log (app/tmp/logs/error*.txt)? >> No

**Comment by sumardika** [comment]
Does .htaccess exist in the root?  >> Yes

<IfModule mod_rewrite.c>
RewriteEngine On

# Some hosts may require you to use the `RewriteBase` directive.
# If you need to use the `RewriteBase` directive, it should be the
# absolute physical path to the directory that contains this htaccess file.
#
# RewriteBase /

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.php [L]
</IfModule>

**Comment by nomadicjosh** [comment]
There are permission issues you must fix so that etSIS can write to and read the files that are missing. Currently, it can create (file_put_contents) or read the files it needs.

**Comment by sumardika** [comment]
I moved etsis_tmp to directory above the doc root but same error still occuring

Warning: file_put_contents(/Users/sumardika/etsis_tmp/www/nodes/etsis/rlde.data.node): failed to open stream: No such file or directory in /Users/sumardika/www/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

**Comment by nomadicjosh** [comment]
If you are setting a custom path, paste the savepath(s) you have in config.php.

**Comment by sumardika** [comment]
$app = new \Liten\Liten(
    [
    'cookies.lifetime' => '86400',
    'cookies.savepath' => '/Users/sumardika/etsis_tmp' . DS . $subdomain . DS,
    'file.savepath' => '/Users/sumardika/etsis_tmp' . DS . $subdomain . DS . 'files' . DS
    ]
);

**Comment by nomadicjosh** [comment]
I haven't used Mac's native local environment before, and I am sure it is a permission issue. Have you googled to see if it is a known error with `file_put_contents` and Mac?

**Comment by sumardika** [comment]
Ok. Thx Parker
