### ISSUE TITLE
Hiatus screen

### ISSUE THREAD

**Issue by BereaSchool** [nomadicjosh/eduTrac-SIS#56]
We are trying to create a hiatus for a student. The date fields do not work and when submitted, we get the error on the attached screenshot.  Thanks for the help!
<img width="1266" alt="screen shot 2018-02-26 at 3 23 59 pm" src="https://user-images.githubusercontent.com/35111092/36693384-1d04cb50-1b09-11e8-9905-790012fa4e62.png">

**Comment by nomadicjosh** [comment]
Looking into it.

**Comment by nomadicjosh** [comment]
I fixed constraint for the database error and also fixed the datepicker.

**Comment by BereaSchool** [comment]
Thank you so much!
