### ISSUE TITLE
Student Header/ Hiatus Field

### ISSUE THREAD

**Issue by BereaSchool** [nomadicjosh/eduTrac-SIS#57]
We've noticed that the latest fix now updates every students' record.  We created a hiatus for one student, and now all our student profile headers show that hiatus.

**Comment by nomadicjosh** [comment]
If you clear the etSIS cache, does it still show for every student?

**Comment by BereaSchool** [comment]
Yes, it still does.

**Comment by nomadicjosh** [comment]
Can you give me some id's where you see this is happening because I checked out a few and I don't see it. I looked at the header's on the SPRO screen, unless you are seeing an issue on a different screen.

**Comment by BereaSchool** [comment]
I had removed it.  I recreated the error by creating a hiatus on #1411 who originally caused the error.  I did a random spot check on 1311, 1458 and 1394. They all have the DISM hiatus on the status bar caused by the one on 1411.

**Comment by nomadicjosh** [comment]
Thanks, this should be fixed now.

**Comment by BereaSchool** [comment]
Thank you!
